## Data
The ```make_binary``` function creates ```n``` instances of $x_1 + x_2 = y$ input output pairs in the form of their binary representations. For instance, calling the function ```make_binary(1)``` will return two tensors that might be 


```[[[0 0]       [[[0]  <- 2^0
  [1 1]         [0]  <- 2^1
  [0 0]         [1]  ...
  [1 0]         [1]
  [0 1]         [1]
  [1 1]         [0]
  [1 1]         [1]
  [0 0]]]       [1]] <- 2^7
(106 + 114   =   220)
```

Where each pair of [0 1] is added to a [1] output (and the RNN is expected to remember the carry implicitly and pass it on to the rest of the sequence)

## Task: Create an RNN which uses the input-output pairs and learns to add. The expected accuracy is 100%


In [1]:
import numpy as np
BATCH_SIZE = 64
n_batches = 250
Number_of_Samples = BATCH_SIZE*n_batches
MAX_DIGITS = 8

################################################
binary = np.unpackbits(np.array([range(2**MAX_DIGITS)],dtype=np.uint8).T,axis=1)
n = 10
def make_binary(n = Number_of_Samples, max_digits = MAX_DIGITS):
    x = np.random.randint(0, 2**max_digits/2, 2*n).reshape(n, 2)
    y = np.sum(x, axis = 1)
    x = np.transpose(binary[x], [0, 2, 1])
    y = binary[y]
    y = np.transpose(y[np.newaxis, :], (1, 2, 0))
    x, y = np.fliplr(x), np.fliplr(y)   
    return(x, y)

def make_decimal(X, y):
    bin2dec = lambda x: int("".join(str(i) for i in reversed(x)), 2)
    X = np.apply_along_axis(func1d=bin2dec, arr=X, axis=1)
    y = np.apply_along_axis(func1d=bin2dec, arr=y, axis=1)
    return(X, y)

#This is going be the format of your data
a, b = make_binary(1)
print(a)
print(b)

#This is to get convert the binary data back to decimal data.
c, d = make_decimal(a, b)
print(c, d)


[[[1 0]
  [0 1]
  [0 1]
  [0 0]
  [0 0]
  [0 0]
  [1 0]
  [0 0]]]
[[[1]
  [1]
  [1]
  [0]
  [0]
  [0]
  [1]
  [0]]]
[[65  6]] [[71]]


## Create your own rnn `model` and train it on data, below

### TESTING YOUR CODE. DO NOT MODIFY THIS############

In [5]:
x, y = make_binary(10)
preds = model.predict_classes(x, verbose=0)
x, preds = make_decimal(x, preds)
result = zip(x, preds)
for tup in result:
	print('Inputs: {}, Prediction: {}'.format(tup[0], tup[1][0]))

Inputs: [100  48], Prediction: 148
Inputs: [34 13], Prediction: 47
Inputs: [35 69], Prediction: 104
Inputs: [49 66], Prediction: 115
Inputs: [ 8 75], Prediction: 83
Inputs: [61 21], Prediction: 82
Inputs: [47 48], Prediction: 95
Inputs: [107  21], Prediction: 128
Inputs: [31 64], Prediction: 95
Inputs: [94 12], Prediction: 106


## Python/Numpy Activity
Try to recreate the data creater function. 